name: 1. Calculate & Analyze (Kalshi)

on:
  schedule:
    # Polymarket과 5분 시차 (05, 20, 35, 50분)
    - cron: '5-59/15 * * * *'
  workflow_dispatch:

jobs:
  calculate:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Private Brain
        uses: actions/checkout@v4
        with:
          repository: bohmec/kalshi-core # [수정] 본인 저장소명
          token: ${{ secrets.TOKEN1 }}
          path: private-brain

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Libraries
        run: pip install -r private-brain/requirements.txt

      - name: Run Engine
        env:
          KALSHI_KEY_ID: ${{ secrets.KALSHI_KEY_ID }}
          KALSHI_PRIVATE_KEY: ${{ secrets.KALSHI_PRIVATE_KEY }}
        run: |
          cd private-brain
          python main.py

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: nexus-data
          path: private-brain/data_output/

          retention-days: 1
